### ISSUE TITLE
Test out a change to the JULIA_DEPOT_PATH

### ISSUE THREAD

**Issue by jlperla** [ubcecon/syzygy#1]
As discussed, we need to see if we can get multiple depots working correctly.

I believe the trick is to set the `JULIA_DEPOT_PATH` environment variable to first point at the local users location (maybe `~/.julia` or is it `~/.`?) as the first in the path, and then the shared one as the second.

**Comment by arnavs** [comment]
Bit of a snag. When we try this in the Dockerfile, we get something like `/bin/sh: 1: /home/jupyter/.julia: not found` (because it's running from some `/bin/sh` somewhere). But `/home/jupyter/.julia` is the correct path (see below). So will need to connect this. 

```
jupyter@bfa009028c28:~/.julia$ pwd
/home/jupyter/.julia
```

**Comment by jlperla** [comment]
But isn't this just for when the user's kernel starts up?  It isn't for the docker image building?  Or maybe I misunderstand.

**Comment by arnavs** [comment]
Done at ea888a1. This approach was hard to work, so what I did was just nuke the duplicate registry in the shared folder (after we use it to install packages). That way, each user is only presented with one registry, the one that's cloned in `~/.julia/registries` when you try to add a package. 

This also helps ensure the immutability of what we give to users in the shared folder, since that folder is not editable by end users, and it doesn't have a Registry. 

And we get the desired: 

```
julia> pathof(QuantEcon) # Package that came with my account. 
"/opt/julia-1.0.0/local/share/julia/packages/QuantEcon/7w41U/src/QuantEcon.jl"

julia> pathof(Flux) # Package I installed. 
"/home/jupyter/.julia/packages/Flux/UHjNa/src/Flux.jl"
```
